# Set current working directory
# File location:
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# Read data from a .dat file generated by "gensvmdat" and stored in the folder "gensvmdat_out"
# (Note that we first need to erase manually the "*" characters) (we do it manually, there are very few of them compared with p)
raw.data <- read.table('./gensvmdat_out/size1000.dat') #size30.dat / size100.dat / size1000.dat
# Dimensions
n <- nrow(raw.data); p <- ncol(raw.data)
# Check variable types (must be all numeric for ridge regression and support vector machines)
str(raw.data)

# Response value: y
y <- raw.data[,p]
y <- data.frame(seq(1,n),y)

# Predictors: A
A <- raw.data[,1:p-1]
A <- data.frame(seq(1,n),A)


# File where data is going to be written (inside input folder)
ampl_data.file <- './input/size1000.dat'

write.table(y, file = ampl_data.file, row.names = FALSE, col.names = FALSE)
write.table(A, file = ampl_data.file, row.names = FALSE, col.names = FALSE, append = TRUE)
